---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 20:31
---
require("Framework.GameManager")
---@class game : GameManager
game = GameManager:extend()

function game:new()
    game.super.new(self)
    bf = require("Framework.breezefield.init")
    require("Framework.World")
    require("Framework.Element")
    require("Framework.Camera")
    ---@type World
    self.world = World(0,9.81,true)
    self:addWorld(self.world)
    self.ground = Element(self.world,"Rectangle",{800,600,1600,200})
    self:addElement(self.ground)
    self.ground:setType(Body.Bodytype.static)
    self.player = Element(self.world,"Rectangle",{450,100,200,200})
    self.player:setType(Body.Bodytype.dynamic)

    self.cam = Camera(self.world,0,0,self.player,1,0,true)
    self:addCamera(self.cam)

end

function game:mousepressed(x, y, button, istouch, presses)
    if (self.player:getX()<x) then
        self.player.body:applyForce(50000,0,0,0)
    else
        self.player.body:applyForce(-50000,0,0,0)
    end
end