---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 14:02
---
function  love.load()
    Object = require("Framework.classic")
    require("game.game")
    game = game()
    love.window.setMode(1600,920)


end


function love.update(dt)
    game:update(dt)
end

function love.draw()
   game:draw()
end

function love.mousepressed(x, y, button, istouch, presses)
    if (game.mousepressed ~= nil) then
        game:mousepressed(x, y, button, istouch, presses)
    end

end