---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tanulo.
--- DateTime: 2022. 09. 28. 15:25
---
---@class Camera : Object
Camera = Object:extend()
---@param world World
---@param x number
---@param y number
---@param element Element
---@param zoom number
---@param smooth boolean
function Camera:new(world,x,y,element,zoom,rot,smooth,rotation_allowed)
    local cam = require("Framework.camera_object")
    self.world = world
    self.element = element or nil
    self.rotation_allowed = rotation_allowed or false
    if self.element then
        self.rot = rot or 0
        self.lx = element.body:getX()
        self.ly = element.body:getX()
        self.zoom = zoom or 1
        self.smooth = smooth or true
    else
        self.rot = rot or 0
        self.lx = x or 0
        self.ly = y or 0
        self.zoom = zoom or 1
        self.smooth = smooth or 0

    end
    self.cam = cam.new(self.lx,self.ly,self.zoom,self.rot,self.smooth)

end

function Camera:draw(elements)
    local hud_components = {}
    local non_hud_components = {}
    for i,v in pairs(elements) do
        if v.hud_element then
            table.insert(hud_components,v)
        else
            table.insert(non_hud_components,v)
        end
    end
    self.cam:attach()
    self.world.world:draw()
    for i,v in pairs(non_hud_components) do
        v:draw()
    end
    self.cam:detach()
    for i,v in pairs(hud_components) do
        v:draw()
    end
end

function Camera:update(dt)
    if (self.element ~= nil) then
        self.lx,self.ly = self.element.body:getX(),self.element.body:getY()
        self:lookAt(self.lx,self.ly)
        if (self.rotation_allowed) then
            self.rot = self.element.body:getAngle()
            self:setRotation(self.rot)
        end
    end
end

function Camera:lookAt(x,y)
    self.cam:lookAt(x,y)
    
end

function Camera:move(x,y)
    self.cam:move(x,y)
end

function Camera:getPosition()
    return self.cam:position()
end

---@param angle number radián
function Camera:rotate(angle)
    self.cam:rotate(angle)
end

function Camera:setRotation(angle)
    self.cam:rotateTo(angle)
end

function Camera:Zoom(zoom)
    self.cam:zoom(zoom)
end

function Camera:setZoom(zoom)
    self.cam:zoomTo(zoom)
end