---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 14:16
---
---@class Element : Body
require("Framework.Body")
Element = Body:extend()

function Element:new(world,type,draw_arguments)
    Element.super.new(self,nil)
    self.world = world
    self.type = type or "Rectangle"
    self.draw_arguments = draw_arguments or {50,50,100,100,0}
    ---@type collider_object
    self.body = world.world:newCollider(self.type,self.draw_arguments)
end
