---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 14:32
---
---@class Fixture : Object
Fixture = Object:extend()
---@param body Body
---@param shape Shape
---@param density number
function Fixture:new(body, shape, density)
    self.body = body
    self.shape = shape
    self.density = density or 1
    self.fixture = love.physics.newFixture(self.body,self.shape,self.density)
end

function Fixture:destroy()
    self.fixture:destroy()
end

function Fixture:getBody( )
    return self.fixture:getBody( )
end

function Fixture:getBoundingBox( index )
    return self.fixture:getBoundingBox( index )
end

function Fixture:getCategory( )
    return self.fixture:getCategory( )
end

function Fixture:getDensity( )
    return self.fixture:getDensity( )
end

function Fixture:getFilterData( )
    return self.fixture:getFilterData( )
end

function Fixture:getFriction( )
    return self.fixture:getFriction( )
end

function Fixture:getGroupIndex( )
    return self.fixture:getGroupIndex( )
end

function Fixture:getMask( )
    return self.fixture:getMask( )
end

function Fixture:getMassData( )
    return self.fixture:getMassData( )
end

function Fixture:getRestitution( )
    return self.fixture:getRestitution( )
end

function Fixture:getShape( )
    return self.fixture:getShape( )
end

function Fixture:getUserData( )
    return self.fixture:getUserData( )
end

function Fixture:isDestroyed( )
    return self.fixture:isDestroyed( )
end

function Fixture:isSensor( )
    return self.fixture:isSensor( )
end

function Fixture:rayCast( x1, y1, x2, y2, maxFraction, childIndex )
    return self.fixture:rayCast( x1, y1, x2, y2, maxFraction, childIndex )
end

function Fixture:setCategory( category1, category2, ... )
    self.fixture:setCategory( category1, category2, ... )
end

function Fixture:setDensity( density )
    self.fixture:setDensity( density )
end

function Fixture:setFilterData( categories, mask, group )
    self.fixture:setFilterData( categories, mask, group )
end

function Fixture:setFriction( friction )
    self.fixture:setFriction( friction )
end

function Fixture:setGroupIndex( group )
    self.fixture:setGroupIndex( group )
end

function Fixture:setMask( mask1, mask2, ... )
    self.fixture:setMask( mask1, mask2, ... )
end

function Fixture:setRestitution( restitution )
    self.fixture:setRestitution( restitution )
end

function Fixture:setSensor( sensor )
    self.fixture:setSensor( sensor )
end

function Fixture:setUserData( value )
    self.fixture:setUserData( value )
end

function Fixture:testPoint( x, y )
    return self.fixture:testPoint( x, y )
end