---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 20:07
---
---@class GameManager : Object
GameManager = Object:extend()
function GameManager:new()
    self.currentWorld = nil
    self.currentCamera = nil
    self.elements = {}
end
---@param world World
function GameManager:addWorld(world)
    require("Framework.World")
    if self.currentWorld ~= nil then
        self.currentWorld:destroy()
        self.elements = {}
    end
    self.currentWorld = world
end
---@param camera Camera
function GameManager:addCamera(camera)
    self.currentCamera = camera
end

function GameManager:addElement(element_table)
    table.insert(self.elements,element_table)
end

function GameManager:update(dt)
    if (self.currentWorld ~= nil) then
        if (self.currentCamera ~= nil) then
            self.currentCamera:update(dt)
        end
        self.currentWorld.world:update(dt)
    end
end

function GameManager:draw()
    if (self.currentWorld ~= nil) then
        if (self.currentCamera ~= nil) then
            self.currentCamera:draw(self.elements)
        else
            self.currentWorld.world:draw()
        end
    end
end

function GameManager:mousepressed(x, y, button, istouch, presses)

end