---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 14:26
---
---@class Shape : Object
Shape = Object:extend()

function Shape:new()
    self.shape = nil
end

function Shape:computeAABB( tx, ty, tr, childIndex )
    return self.shape:computeAABB( tx, ty, tr, childIndex )
end

function Shape:computeMass( density )
    return self.shape:computeMass( density )
end

function Shape:getChildCount( )
    return self.shape:getChildCount( )
end

function Shape:getRadius()
    return self.shape:getRadius()
end

function Shape:getType( )
    return self.shape:getType( )
end

function Shape:rayCast( x1, y1, x2, y2, maxFraction, tx, ty, tr, childIndex )
    return self.shape:rayCast( x1, y1, x2, y2, maxFraction, tx, ty, tr, childIndex )
end