---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 30. 14:07
---
---@class World : Object
World = Object:extend()
---@param size number Egy méter pixelben
---@param gx number x gravitáció
---@param gy number y gravitáció
function World:new(gx,gy,sleep)
    local bf = require("Framework.breezefield.init")
    self.sleep = sleep or true
    self.size = size or 64
    self.gx = gx or 0
    self.gy = 10*gy or 10*9.81
    love.physics.setMeter(self.size)
    self.world = bf.newWorld(self.gx,self.gy,self.sleep)
    self.objects = {}
end

function World:destroy()
    self.world:destroy()
end

function World:getBodies()
    return self.world:getBodies()
end

function World:getBodyCount()
    return self.world:getBodyCount()
end

function World:getCallbacks()
    return self.world:getCallbacks()
end

function World:getContactCount()
    return self.world:getContactCount()
end

function World:getContactFilter()
    return self.world:getContactFilter()
end

function World:getContacts()
    return self.world:getContacts()
end

function World:getGravity()
    return self.world:getGravity()
end

function World:getJoinCount()
    return self.world:getJointCount()
end

function World:getJoints()
    return self.world:getJoints()
end

function World:isDestroyed()
    return self.world:isDestroyed()
end

function World:isLocked()
    return self.world:isLocked()
end
function World:isSleepingAllowed()
    return self.world:isSleepingAllowed()
end
---@param topLeftX number
---@param topLeftY number
---@param bottomRightX number
---@param bottomRightY number
---@param callback function
function World:queryBoundingBox(topLeftX, topLeftY, bottomRightX, bottomRightY, callback)
    self.world:queryBoundingBox(topLeftX,topLeftY,bottomRightX,bottomRightY,callback)
end
---@param x1 number
---@param y1 number
---@param x2 number
---@param y2 number
---@param callback function
function World:rayCast(x1, y1, x2, y2, callback)
    self.world:rayCast(x1, y1, x2, y2, callback)
end
---@param beginContact function
---@param endContact function
---@param preSolve function
---@param postSolve function
function World:setCallbacks(beginContact, endContact, preSolve, postSolve)
    self.world:setCallbacks(beginContact, endContact, preSolve, postSolve)
end
---@param filter function
function World:setContactFilter(filter)
    self.world:setContactFilter(filter)
end
---@param x number
---@param y number
function World:setGravity(x,y)
    self.world:setGravity(x,y)
end
---@param allow boolean
function World:setSleepingAllowed(allow)
    self.world:setSleepingAllowed(allow)
end
---@param x number
---@param y number
function World:translateOrigin(x, y)
    self.world:translateOrigin(x, y)
end
---@param dt number
---@param velocityiterations number
---@param positioniterations number
function World:update(dt, velocityiterations, positioniterations)
    self.world:update(dt, velocityiterations, positioniterations)
end